#!/usr/bin/env python3
"""Render a code-generated protocol-skeleton Markdown file as a Word document.

This is a presentation renderer only.  The protocol matrix and language-pair
catalog remain the rule sources; the Markdown passed here must be generated by
render_protocol_template.py.  The compact-reference-guide preset is used
because the output is a structured completion guide rather than a completed
narrative protocol.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from render_copyable_docx import build


FOOTER = "research-ethics｜代码生成研究计划书骨架｜Code-generated protocol skeleton"


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--markdown", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    try:
        markdown = args.markdown.read_text(encoding="utf-8")
        if "protocol-coverage-matrix.yaml" not in markdown:
            raise ValueError("输入并非由研究计划书骨架生成器产生的 Markdown")
        build(markdown, args.output, footer_text=FOOTER)
    except (OSError, UnicodeError, ValueError) as exc:
        print(f"研究计划书 Word 未生成：{exc}", file=sys.stderr)
        return 2
    print(f"研究计划书 Word 已生成：{args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
